#!/bin/bash
OFF='\e[0m'
BWhite='\e[1;37m'
BYellow='\e[1;33m'
On_White='\e[1;30;43m'
On_Red='\e[1;30;41m'
API-KEY='aksakefkkf3o2fo23olw'

echo -e "${BWhite}###############################################################"
echo -e "## Upload to HYDRAX                                         v##"
echo -e "###############################################################${OFF}"
echo " "

hydraxupload() {
        echo "###############################################################"
        for file in $(ls *.mkv)
        do
                [ -f $file ] && echo -e "\nUploading:${BYellow} $file ${BWhite}" && curl -F "file=@$file" up.hydrax.net/${API-KEY}
        done
        echo -e "\n###############################################################${OFF}"
}

tanyasatu() {
        echo -e "${On_White} Apakah ingin menguploadke HYDRAX file di folder ini? ${OFF}${BWhite} "
        read -p " Masukan Pilihan: (y/n) " RESP
        if [ "$RESP" = "y" ]; then
          hydraxupload
        else
          echo -e "${On_Red} Byee.. ${OFF}\n"
        fi
}

tanyasatu
